# Dockerfile for the ICS 211 Lab 3 SOP Web Server
#
FROM php:5.6-apache
LABEL maintainer="Jason Cumiskey <cumiskey@camosun.bc.ca>"

COPY ports.conf /etc/apache2/
COPY 000-default.conf /etc/apache2/sites-available/
